# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Template_config = debug
endif
ifeq ($(config),release)
  Template_config = release
endif

PROJECTS := Template

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Template:
ifneq (,$(Template_config))
	@echo "==== Building Template ($(Template_config)) ===="
	@${MAKE} --no-print-directory -C . -f Template.make config=$(Template_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f Template.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Template"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"